### ISSUE TITLE
After a while rqt_plot stops sidescrolling

### ISSUE THREAD

**Issue by HWiese1980** [ros-visualization/rqt_plot#10]
I'm experiencing the following weird behavior of `rqt_plot`: https://youtu.be/D7zrege--iw

The two topics are std_msgs/Float32 with queue_size=1.

**Comment by HWiese1980** [comment]
Behavior is independent of used backend. Happens with matplotlib as well as with pyqtgraph.

**Comment by dirk-thomas** [comment]
Please provide a minimal example / steps to reproduce the problem as well as include information about what versions you are using.
