### ISSUE TITLE
can't find the correct system package for module Qwt

### ISSUE THREAD

**Issue by jacknlliu** [ros-visualization/rqt_plot#12]
For https://github.com/ros-visualization/rqt_plot/blob/549bbcb0b14252ee91dfdab38735bc08f19c7a24/src/rqt_plot/data_plot/qwt_data_plot.py#L40
we can't find the correct system package for module Qwt, but just find `qwt`.

What is the correct system package for using qwtplot?

**Comment by dirk-thomas** [comment]
The package manifest states the ROS package it depend on:

https://github.com/ros-visualization/rqt_plot/blob/549bbcb0b14252ee91dfdab38735bc08f19c7a24/package.xml#L24

That ROS package has the following in its manifest:

https://github.com/ros-visualization/qwt_dependency/blob/6be64242d82281f9e8727543c53fcdfd08058bdf/package.xml#L11-L12

Afaik there is no Python package for Qwt 6.1+ available atm. At least that is the case for ROS Kinetic and newer which uses Qt 5.

For ROS Indigo / Qt 4 the dependency is `python-qwt5-qt4` (as can be seen on the indigo branch).
