### ISSUE TITLE
Native rqt_plot with QtCharts?

### ISSUE THREAD

**Issue by martonmiklos** [ros-visualization/rqt_plot#23]
Hi guys,

I have some missing features from the Matplotlib based plot plugin namely:
 * Show/hide individual plots by clicking on the legend
 * Add multiple Y axes and allow plots assigned to different axes (when tweaking PID controller it would be very useful)
 * Zoom with mouse wheel
 * Instantly editable axis scale: https://www.youtube.com/watch?v=Ab1aIiMawGA&feature=youtu.be

I have written some Qt applications where the I have used QtCharts where I have implemented the features mentioned above. What do you think would it be useful to create a C++ plot plugin where these features would be implemented?

**Comment by dirk-thomas** [comment]
I am not sure if [rqt_multiplot](https://github.com/anybotics/rqt_multiplot_plugin) addresses any of these but I just wanted to mention it.

The question is if either of these features could be implemented by enhancing any of the existing plugins or not. If not, creating yet another plotting plugin is certainly an option.

**Comment by martonmiklos** [comment]
Thanks for the suggestion, I was not aware of the existence of that plugin. I have checked it briefly, and it fits my use case better (has support for multiple Y axes).
