### ISSUE TITLE
rqt_plot crashes with AttributeError: NoneType object has no attribute __slots__ when typing in name of unknown message class

### ISSUE THREAD

**Issue by pumaking** [ros-visualization/rqt_plot#25]
When the message class of the topic typed in to be plotted does not exit, rqt_plot crashes with the following error:

```
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_plot/plot_widget.py", line 210, in on_topic_edit_textChanged
    plottable, message = is_plottable(topic_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_plot/plot_widget.py", line 110, in is_plottable
    fields, message = get_plot_fields(topic_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_plot/plot_widget.py", line 93, in get_plot_fields
    for i, slot in enumerate(field_class.__slots__):
AttributeError: 'NoneType' object has no attribute '__slots__'
Aborted (core dumped)
```

I would expect a warning or message here instead of an abort.

**Comment by dirk-thomas** [comment]
Can you please include exact steps to reproduce the problem as well as the version of the `ros-melodic-rqt-plot` package you are using.

**Comment by pumaking** [comment]
I'm using the latest rqt-plot version for bionic (0.4.8):
```
$ sudo apt upgrade ros-melodic-rqt-plot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-melodic-rqt-plot is already the newest version (0.4.8-0bionic.20181112.194807).
```

I've attached a package that builds a custom message to reproduce the problem.

[package.zip](https://github.com/ros-visualization/rqt_plot/files/2920814/package.zip)

1. Unzip the package and run build.sh to compile the message (this just runs cmake and make).
2. Start a roscore
3. Run `source build/devel/setup.bash` in the `package/` folder.
4. Run `rosrun package publish.py`. This just publishes the custom message to the topic "msg".
5. Open rqt_plot.
6. Type in "msg" in the topic search bar. Upon pressing 'g', rqt_plot crashes for me. If the setup script is sourced, this does not happen.

**Comment by dirk-thomas** [comment]
Please see #26 for the proposed fix.

**Comment by pumaking** [comment]
Thank you! I've tested https://github.com/ros-visualization/rqt_plot/pull/26 and rqt_plot no longer crashes for me for unknown messages.

**Comment by dirk-thomas** [comment]
> I've tested #26 and rqt_plot no longer crashes for me for unknown messages.

Thanks for reporting back!
