### ISSUE TITLE
ROS2 rqt plot crashes when passing a topic name from the command line

### ISSUE THREAD

**Issue by ralph-lange** [ros-visualization/rqt_plot#27]
The Plot plugin of ROS 2 rqt crashes when calling it with a topic name from the command line, i.e. when invoking it with `rqt -s Plot --args /topicname`.

https://github.com/ros-visualization/rqt_plot/blob/crystal-devel/src/rqt_plot/plot.py#L125 expects two return values from Node.get_topic_names_and_types() whereas this function in https://github.com/ros2/rclpy/blob/master/rclpy/rclpy/node.py#L769 seems to return a single List (of tuples) only.

**Comment by dirk-thomas** [comment]
Please see #33 for the fix.

**Comment by dirk-thomas** [comment]
Thanks for reporting the problem. Please see #33 for the fix.
