### ISSUE TITLE
rqt_plot on ros-crystal: exception when accessing subfields of a geometry_msgs::Point message

### ISSUE THREAD

**Issue by bergercookie** [ros-visualization/rqt_plot#28]
A common hack that used to work on rqt - ROS1 versions was the following way of accessing the x,y,z coordinates of a Pose / Point message.

Suppose I 'm publishing a PoseStamped message in the global namespace: /pose

Then in rqt_plot I could write the following in the rqt_plot form for visualising the `x` coordinate of the pose position part:

`/pose/pose/position/x`.

Now, when I'm trying to do the same thing for rqt_plot on crystal I'm getting the following error:

```
AttributeError: 'NoneType' object has no attribute 'get_fields_and_field_types'
Traceback (most recent call last):
  File "/opt/ros/crystal/lib/python3.6/site-packages/rqt_plot/plot_widget.py", line 256, in on_topic_edit_textChanged
    plottable, message = is_plottable(self._node, topic_name)
  File "/opt/ros/crystal/lib/python3.6/site-packages/rqt_plot/plot_widget.py", line 151, in is_plottable
```

**Comment by clalancette** [comment]
I know this is a very old ticket, but I've just retested this on the latest Rolling (soon to become Humble), and this seems to work fine.  So I'm going to go ahead and close this out, but do feel free to reopen if this is still a problem for you.
