### ISSUE TITLE
rqt_plot doesn't show published topic

### ISSUE THREAD

**Issue by jonathan84clark** [ros-visualization/rqt_plot#55]
I can't get any graphs or visualizations using rqt_plot
Steps to reproduce
1. rostopic list
I get this 
`/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/rosout
/rosout_agg
/sonar_sensor1/range_finder
/sonar_sensor1/range_finder/parameter_descriptions
/sonar_sensor1/range_finder/parameter_updates
/sonar_sensor10/range_finder
/sonar_sensor10/range_finder/parameter_descriptions
/sonar_sensor10/range_finder/parameter_updates
/sonar_sensor11/range_finder
/sonar_sensor11/range_finder/parameter_descriptions
/sonar_sensor11/range_finder/parameter_updates
/sonar_sensor12/range_finder
/sonar_sensor12/range_finder/parameter_descriptions
/sonar_sensor12/range_finder/parameter_updates
/sonar_sensor13/range_finder
/sonar_sensor13/range_finder/parameter_descriptions
/sonar_sensor13/range_finder/parameter_updates
/sonar_sensor14/range_finder
/sonar_sensor14/range_finder/parameter_descriptions
/sonar_sensor14/range_finder/parameter_updates
/sonar_sensor15/range_finder
/sonar_sensor15/range_finder/parameter_descriptions
/sonar_sensor15/range_finder/parameter_updates
/sonar_sensor16/range_finder
/sonar_sensor16/range_finder/parameter_descriptions
/sonar_sensor16/range_finder/parameter_updates
/sonar_sensor2/range_finder
/sonar_sensor2/range_finder/parameter_descriptions
/sonar_sensor2/range_finder/parameter_updates
/sonar_sensor3/range_finder
/sonar_sensor3/range_finder/parameter_descriptions
/sonar_sensor3/range_finder/parameter_updates
/sonar_sensor4/range_finder
/sonar_sensor4/range_finder/parameter_descriptions
/sonar_sensor4/range_finder/parameter_updates
/sonar_sensor5/range_finder
/sonar_sensor5/range_finder/parameter_descriptions
/sonar_sensor5/range_finder/parameter_updates
/sonar_sensor6/range_finder
/sonar_sensor6/range_finder/parameter_descriptions
/sonar_sensor6/range_finder/parameter_updates
/sonar_sensor7/range_finder
/sonar_sensor7/range_finder/parameter_descriptions
/sonar_sensor7/range_finder/parameter_updates
/sonar_sensor8/range_finder
/sonar_sensor8/range_finder/parameter_descriptions
/sonar_sensor8/range_finder/parameter_updates
/sonar_sensor9/range_finder
/sonar_sensor9/range_finder/parameter_descriptions
/sonar_sensor9/range_finder/parameter_updates
/vrx/debug/wind/direction
/vrx/debug/wind/speed
/wamv/joint_states
/wamv/sensors/gps/gps/fix
/wamv/sensors/gps/gps/fix/position/parameter_descriptions
/wamv/sensors/gps/gps/fix/position/parameter_updates
/wamv/sensors/gps/gps/fix/status/parameter_descriptions
/wamv/sensors/gps/gps/fix/status/parameter_updates
/wamv/sensors/gps/gps/fix/velocity/parameter_descriptions
/wamv/sensors/gps/gps/fix/velocity/parameter_updates
/wamv/sensors/gps/gps/fix_velocity
/wamv/sensors/imu/imu/data
/wamv/sensors/imu/imu/data/accel/parameter_descriptions
/wamv/sensors/imu/imu/data/accel/parameter_updates
/wamv/sensors/imu/imu/data/bias
/wamv/sensors/imu/imu/data/rate/parameter_descriptions
/wamv/sensors/imu/imu/data/rate/parameter_updates
/wamv/sensors/imu/imu/data/yaw/parameter_descriptions
/wamv/sensors/imu/imu/data/yaw/parameter_updates
/wamv/thrusters/bow_thrust_angle
/wamv/thrusters/bow_thrust_cmd
/wamv/thrusters/main_thrust_angle
/wamv/thrusters/main_thrust_cmd
/wamv/thrusters/stern_thrust_angle
/wamv/thrusters/stern_thrust_cmd
`
2. Launched rqt_plot from the terminal
`rqt_plot /vrx/debug/wind/speed`
Empty window is displayed

3. Launched rqt_plot without a topic from the terminal
`rqt_plot`
Entered the topic /vrx/debug/wind/speed into the rqt_plot window
The window remained empty.

FYI: Information on wind speed topic:
`rostopic info /vrx/debug/windpeed
Type: std_msgs/Float64

Publishers: 
 * /gazebo (http://192.168.1.29 :37629/)

Subscribers: 
 * /rqt_gui_py_node_9516 (http://192.168.1.29 :36689/)
 * /rqt_gui_py_node_24809 (http://192.168.1.29 :43971/)
`

Any help would be great!

Thanks,

Jonathan L Clark

**Comment by jonathan84clark** [comment]
Oh I see what is going on now.

Since it crashes when I resize the window, and I need to resize or maximize the window to see the data I have never seen the data.
Please see https://github.com/ros-visualization/rqt_plot/issues/54

**Comment by clalancette** [comment]
Based on the last comment, I'm going to close this out.  The problem should be solved when #54 is solved.
