### ISSUE TITLE
Unable to add topic to plot 

### ISSUE THREAD

**Issue by flieger19** [ros-visualization/rqt_plot#62]
While selecting an active topic in the MatPlot plugin window, the GUI plus button stays inactive and the topic data can not be plotted. We're running ros2 dashing on Debian 10 and ros2 eloquent on Ubuntu 18.04. We're  encountering the described problem on both systems and distributions.

**Comment by Aposhian** [comment]
I am also experiencing this issue on ros2 foxy. What was done to resolve this issue?

**Comment by NehilDanis** [comment]
I am experiencing the same issue with ros melodic, has anything done to resolve this issue?

**Comment by fhwedel-hoe** [comment]
This issue may be closed, but the problem remains. I experience this on Ubuntu 20.04 with ROS 2 foxy. I did some investigations and noticed all topics I wanted to plot were not deemed plottable. They are primitive float32 topics. I overcame this problem by explicitly allowing topics to be regarded as their nested field path. It works for me, but I have no idea what this does for anyone else.

    --- tmp/plot_widget.py
    +++ opt/ros/foxy/lib/python3.8/site-packages/rqt_plot/plot_widget.py
    @@ -86,8 +86,9 @@
         if topic_type_str is None:
             message = "no topic types found for topic %s " % (topic_name)
             return [], message
    -
    -    if len(topic_name) < len(real_topic) + 1:
    +    if topic_name == real_topic:
    +        nested_field_path = topic_name
    +    elif len(topic_name) < len(real_topic) + 1:
             message = 'no field specified in topic name "{}"'.format(topic_name)
             return [], message

**Comment by Tanneguydv** [comment]
Thank you, @fhwedel-hoe I had the same issue on ROS2 Humble Ubuntu 22.04 and the trick works
