### ISSUE TITLE
in pyqtgraph,Can't draw at the same time between  both topic with stamped and topic without stamped?

### ISSUE THREAD

**Issue by JackRen88** [ros-visualization/rqt_plot#75]
hello,everyone!
I want to plot at the same time between  both topic with stamped and topic without stamped in pyqtgraph,however,I found that rqt_plot(rqt) can't .should I deal with it ?

**Comment by clalancette** [comment]
The fact that it is stamped or not stamped shouldn't have much to do with it; you should be able to plot arbitrary topics using rqt_plot.  One restriction you may run into is https://github.com/ros-visualization/rqt_plot/issues/68 , but that should be a relatively uncommon situation.

If you still have questions here, I'll suggest posting to https://answers.ros.org, which is our central question and answer site.  I'll close this out for now.
