### ISSUE TITLE
ROS 2: topic list should be a drop-down box

### ISSUE THREAD

**Issue by clalancette** [ros-visualization/rqt_plot#80]
It would be nice if the "Topic" box was a drop-down that showed all existing topics, as well as be editable so arbitrary topics could be entered in.  This would be a little more user-friendly, especially for first-time users that don't know the syntax for plotting a topic.

**Comment by mjeronimo** [comment]
@clalancette The topic box is editable and expands each level upon entering a '/' character (see attached video). So, one can drill down all the way to the fields that can be plotted.

https://user-images.githubusercontent.com/865395/163867135-fec33962-e63a-4a39-ad73-cdff3d268099.mp4

**Comment by clalancette** [comment]
OK, yeah, I guess I was misusing it before.  That's fine for now, I'll close this out.
